---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web-doc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-doc-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-doc-app
    spec:
      containers:
      - image: mbps54/web_doc_app:2.3
        name: web-doc-app
        env:
          - name: SERVER_NAME_IP
            value: '0.0.0.0'
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 20
        startupProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 20
          periodSeconds: 10
...